name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: false

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Test
        run: go test -v -race ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
         version: v1.54

      - name: Coverage
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - name: Build
        run: go build -v ./...